### ISSUE TITLE
add register user and restful api 

### ISSUE THREAD

**Issue by htoooth** [phodal/moqi.mobi#3]
hi, your project help me a lot. thanks.
I recently also study how to build a mobile web app.  
I hope that the project add user register and restful api.
If you need a help, I do my best to help you.

**Comment by phodal** [comment]
For now,just I developed in this project,I spend more time in simple the development.and I don't have the experience on safe transfer user information.So, I think if you would like to join the project would be helpful.

目前，只有我一个在开发,目前更多地是将时间花在简化开发看，而且没有经验在安全地传输用户信息。我想，如果你乐意加入这个项目，将会带来很大的帮助。
