### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by phodal** [phodal/moqi.mobi#5]

**Comment by notcrydiedgod** [comment]
brother ,what do you do this.

**Comment by phodal** [comment]
https://github.com/gmszone/freerice 在这个项目中，我试图去构建一个类似的系统，但是对于当前这个系统似乎已经没有什么提高了？

**Comment by notcrydiedgod** [comment]
兄弟，我不懂node.js我只会java

**Comment by phodal** [comment]
OK,我再看看吧
